// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArYVc2u2bUPHD8priujvHfMbQ8eiadGeQ',
    appId: '1:214609815288:web:2f17ac52bd72fa9ff67d0d',
    messagingSenderId: '214609815288',
    projectId: 'cloud-kitchen-app-da092',
    authDomain: 'cloud-kitchen-app-da092.firebaseapp.com',
    storageBucket: 'cloud-kitchen-app-da092.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGsNEvRO5yWfIlfL7HVbd4wTRA7nlEk30',
    appId: '1:214609815288:android:2c65417a3e4f552af67d0d',
    messagingSenderId: '214609815288',
    projectId: 'cloud-kitchen-app-da092',
    storageBucket: 'cloud-kitchen-app-da092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9fkgBcUjqtkTDnNnXsghhflAVzXmlZY',
    appId: '1:214609815288:ios:d861214bf99115adf67d0d',
    messagingSenderId: '214609815288',
    projectId: 'cloud-kitchen-app-da092',
    storageBucket: 'cloud-kitchen-app-da092.firebasestorage.app',
    iosBundleId: 'com.example.cloudKitchenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN9fkgBcUjqtkTDnNnXsghhflAVzXmlZY',
    appId: '1:214609815288:ios:d861214bf99115adf67d0d',
    messagingSenderId: '214609815288',
    projectId: 'cloud-kitchen-app-da092',
    storageBucket: 'cloud-kitchen-app-da092.firebasestorage.app',
    iosBundleId: 'com.example.cloudKitchenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArYVc2u2bUPHD8priujvHfMbQ8eiadGeQ',
    appId: '1:214609815288:web:8375092a33bb1a95f67d0d',
    messagingSenderId: '214609815288',
    projectId: 'cloud-kitchen-app-da092',
    authDomain: 'cloud-kitchen-app-da092.firebaseapp.com',
    storageBucket: 'cloud-kitchen-app-da092.firebasestorage.app',
  );
}
